
apiVersion: v1
kind: Service
metadata:
  name: helloworldapp
  labels:
    app: helloworldapp
spec:
  ports:
    - port: 9080
  selector:
    app: helloworldapp
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworldapp
  name: helloworldapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - image: mycluster.icp:8500/default/helloworldapp:latest
        name: helloworldapp
        ports:
        - containerPort: 9080
          protocol: TCP
